import { targets } from './targets';

export const TARGETS: targets[] = [
  { id: 0, name: "Book", cardPath: "../assets/img/Book.png", padPath: null },
  { id: 1, name: "Gold", cardPath: "../assets/img/Gold.png", padPath: null },
  { id: 2, name: "Map", cardPath: "../assets/img/Map.png", padPath: null },
  { id: 3, name: "Crown", cardPath: "../assets/img/Crown.png", padPath: null, },
  { id: 4, name: "Keys", cardPath: "../assets/img/Keys.png", padPath: null },
  { id: 5, name: "Skull", cardPath: "../assets/img/Skull.png", padPath: null },
  { id: 6, name: "Ring", cardPath: "../assets/img/Ring.png", padPath: null },
  { id: 7, name: "Chest", cardPath: "../assets/img/Chest.png", padPath: null },
  { id: 8, name: "Emerald", cardPath: "../assets/img/Emerald.png", padPath: null },
  { id: 9, name: "Sword", cardPath: "../assets/img/Sword.png", padPath: null },
  { id: 10, name: "Candlestick", cardPath: "../assets/img/Candlestick.png", padPath: null },
  { id: 11, name: "Helmet", cardPath: "../assets/img/Helmet.png", padPath: null },
  { id: 12, name: "Bat", cardPath: "../assets/img/Bat.png", padPath: "../assets/img/pads/treasure-pad_bat@150px.png" },
  { id: 13, name: "Djinn", cardPath: "../assets/img/Djinn.png", padPath: "../assets/img/pads/treasure-pad_djinn@150px.png" },
  { id: 14, name: "Dragon", cardPath: "../assets/img/Dragon.png", padPath: "../assets/img/pads/treasure-pad_dragon@150px.png" },
  { id: 15, name: "Fairy", cardPath: "../assets/img/Fairy.png", padPath: "../assets/img/pads/treasure-pad_fairy@150px.png" },
  { id: 16, name: "Ghost", cardPath: "../assets/img/Ghost.png", padPath: "../assets/img/pads/treasure-pad_ghost@150px.png" },
  { id: 17, name: "Kobold", cardPath: "../assets/img/Kobold.png", padPath: "../assets/img/pads/treasure-pad_kobold@150px.png" },
  { id: 18, name: "Beetle", cardPath: "../assets/img/Beetle.png", padPath: "../assets/img/pads/treasure-pad_beetle@150px.png" },
  { id: 19, name: "Lizard", cardPath: "../assets/img/Lizard.png", padPath: "../assets/img/pads/treasure-pad_lizard@150px.png" },
  { id: 20, name: "Mouse", cardPath: "../assets/img/Mouse.png", padPath: "../assets/img/pads/treasure-pad_mouse@150px.png" },
  { id: 21, name: "Moth", cardPath: "../assets/img/Moth.png", padPath: "../assets/img/pads/treasure-pad_moth@150px.png" },
  { id: 22, name: "Owl", cardPath: "../assets/img/Owl.png", padPath: "../assets/img/pads/treasure-pad_owl@150px.png" },
  { id: 23, name: "Spider", cardPath: "../assets/img/Spider.png", padPath: "../assets/img/pads/treasure-pad_spider@150px.png" },
];
