import { targets } from './targets';

export const TARGETS: targets[] = [
  { id: 0, name: "Book", cardPath: "../assets/img/cards/Book.png", padPath: "../assets/img/pads/treasure-pad_book@150px.png" },
  { id: 1, name: "Gold", cardPath: "../assets/img/cards/Gold.png", padPath: "../assets/img/pads/treasure-pad_gold@150px.png" },
  { id: 2, name: "Map", cardPath: "../assets/img/cards/Map.png", padPath: "../assets/img/pads/treasure-pad_map@150px.png" },
  { id: 3, name: "Crown", cardPath: "../assets/img/cards/Crown.png", padPath: "../assets/img/pads/treasure-pad_crown@150px.png", },
  { id: 4, name: "Keys", cardPath: "../assets/img/cards/Keys.png", padPath: "../assets/img/pads/treasure-pad_keys@150px.png" },
  { id: 5, name: "Skull", cardPath: "../assets/img/cards/Skull.png", padPath: "../assets/img/pads/treasure-pad_skull@150px.png" },
  { id: 6, name: "Ring", cardPath: "../assets/img/cards/Ring.png", padPath: "../assets/img/pads/treasure-pad_ring@150px.png" },
  { id: 7, name: "Chest", cardPath: "../assets/img/cards/Chest.png", padPath: "../assets/img/pads/treasure-pad_chest@150px.png" },
  { id: 8, name: "Emerald", cardPath: "../assets/img/cards/Emerald.png", padPath: "../assets/img/pads/treasure-pad_emerald@150px.png" },
  { id: 9, name: "Sword", cardPath: "../assets/img/cards/Sword.png", padPath: "../assets/img/pads/treasure-pad_sword@150px.png" },
  { id: 10, name: "Candlestick", cardPath: "../assets/img/cards/Candlestick.png", padPath: "../assets/img/pads/treasure-pad_candlestick@150px.png" },
  { id: 11, name: "Helmet", cardPath: "../assets/img/cards/Helmet.png", padPath: "../assets/img/pads/treasure-pad_helmet@150px.png" },
  { id: 12, name: "Bat", cardPath: "../assets/img/cards/Bat.png", padPath: "../assets/img/pads/treasure-pad_bat@150px.png" },
  { id: 13, name: "Djinn", cardPath: "../assets/img/cards/Djinn.png", padPath: "../assets/img/pads/treasure-pad_djinn@150px.png" },
  { id: 14, name: "Dragon", cardPath: "../assets/img/cards/Dragon.png", padPath: "../assets/img/pads/treasure-pad_dragon@150px.png" },
  { id: 15, name: "Fairy", cardPath: "../assets/img/cards/Fairy.png", padPath: "../assets/img/pads/treasure-pad_fairy@150px.png" },
  { id: 16, name: "Ghost", cardPath: "../assets/img/cards/Ghost.png", padPath: "../assets/img/pads/treasure-pad_ghost@150px.png" },
  { id: 17, name: "Kobold", cardPath: "../assets/img/cards/Kobold.png", padPath: "../assets/img/pads/treasure-pad_kobold@150px.png" },
  { id: 18, name: "Beetle", cardPath: "../assets/img/cards/Beetle.png", padPath: "../assets/img/pads/treasure-pad_beetle@150px.png" },
  { id: 19, name: "Lizard", cardPath: "../assets/img/cards/Lizard.png", padPath: "../assets/img/pads/treasure-pad_lizard@150px.png" },
  { id: 20, name: "Mouse", cardPath: "../assets/img/cards/Mouse.png", padPath: "../assets/img/pads/treasure-pad_mouse@150px.png" },
  { id: 21, name: "Moth", cardPath: "../assets/img/cards/Moth.png", padPath: "../assets/img/pads/treasure-pad_moth@150px.png" },
  { id: 22, name: "Owl", cardPath: "../assets/img/cards/Owl.png", padPath: "../assets/img/pads/treasure-pad_owl@150px.png" },
  { id: 23, name: "Spider", cardPath: "../assets/img/cards/Spider.png", padPath: "../assets/img/pads/treasure-pad_spider@150px.png" },
];
